version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=polls
      - POSTGRES_USER=polls
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    command: >
      bash -c "sleep 20
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"